-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 20:35:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema s24201596
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema s24201596
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s24201596` DEFAULT CHARACTER SET utf8 ;
USE `s24201596` ;

-- -----------------------------------------------------
-- Table `s24201596`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s24201596`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `address_street` VARCHAR(100) NULL DEFAULT NULL,
  `address_suburb` VARCHAR(50) NULL DEFAULT NULL,
  `address_state` VARCHAR(6) NULL DEFAULT NULL,
  `address_postcode` VARCHAR(4) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(12) NULL DEFAULT NULL,
  `is_subscribed` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s24201596`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s24201596`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s24201596`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s24201596`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `cost_price` DECIMAL(8,2) NULL DEFAULT NULL,
  `sale_price` DECIMAL(8,2) NULL DEFAULT NULL,
  `country_of_origin` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s24201596`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s24201596`.`product_category` (
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  INDEX `fk_product_category_category_idx` (`category_id` ASC),
  INDEX `fk_product_category_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `s24201596`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `s24201596`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s24201596`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s24201596`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s24201596`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s24201596`.`product_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_product_image_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_image_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `s24201596`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `s24201596`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s24201596`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
